FROM node:23-bullseye

WORKDIR /home/node/frontend

# Copy the source code into the container
COPY . .

# Downgrade to npm version 10.8.3, since npm install freezes on version 10.9.0 when running npm install
RUN npm install -g npm@10.8.3 && npm install --save-dev

# Run the development server
CMD ["npm", "run", "dev", "--", "--host"]
